server:
port: 8080


spring:
datasource:
url: jdbc:sqlserver://localhost:1433;databaseName=videodb;encrypt=true;trustServerCertificate=true
username: sa
password: Hieu228!
jpa:
hibernate:
ddl-auto: update # dev: update / none in prod
properties:
hibernate:
dialect: org.hibernate.dialect.SQLServerDialect
open-in-view: false


app:
upload-dir: uploads # thư mục gốc lưu file (tương đối so với project root)
category-subdir: categories


logging:
level:
org.hibernate.SQL: warn