server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=videodb;encrypt=true;trustServerCertificate=true
    username: sa
    password: Hieu228!
    web:
      resources:
        static-locations: classpath:/static/, file:./uploads/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dbo
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  upload-dir: uploads
  category-subdir: categories


